## 9.1 Creating ndarrays

You can create ndarrays in several different [ways](https://docs.scipy.org/doc/numpy/reference/routines.array-creation.html#array-creation-routines) with the functions, that come with importing the numpy library:

In [1]:
import numpy as np

**`np.emtpy`, `np.zeros`, `np.ones`, `np.full`**: Creates a ndarray with empty elements, zeros, ones or a given fill value. You will need to indicate the desired shape of your array in the form: `np.ones((2,3)`, which means two rows, three columns. Furthermore you can indicate the type of data, you want to create within your array: `np.ones(2, dtype = np.bool`. If you use np.full, you must also specify the fill value in the form `np.full((2,3), 5)`.

In [2]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [3]:
np.ones(2, dtype = np.bool)

array([ True,  True])

In [4]:
np.full((2,3), 5)

array([[5, 5, 5],
       [5, 5, 5]])

**`np.array`**: converts existing data into a numpy ndarray. 

In [5]:
a = [1, 2, 3] #this is a list in python
b = [4, 5, 6]

np.array([a,b]) #this is a numpy ndarray --> does not behave like a list!

array([[1, 2, 3],
       [4, 5, 6]])

**`np.arange`**: creates a ndarray startin from the start argument, stepping by the step interval to the stop argument. You will define it in the form `np.arange(start, stop, step)`.
Be careful! the start and stop arguments define the half open interval `[start, stop[`:


In [6]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [7]:
np.arange(0, 10, 2) #10 is left out!!

array([0, 2, 4, 6, 8])