## 9.2 Indexing

Indexing gets quite important with huge datasets where you want to pick out specific data for your analysis. Before we start with indexing in general, it is very important to notice that there a two ways of indexing: basic indexing and advanced indexing. 

### 9.2.1 Basic indexing

If you select a part of your array by basic indexing, this will only create a **view** on the original array! The new array uses the same memory slot as the old array, but the data pointer only picks out the selected pieces of this old array. That means, if you change your newly created array, the original array will be changed as well. 

In [8]:
a = np.full((2,3),10)
a

array([[10, 10, 10],
       [10, 10, 10]])

In [9]:
b = a[0:1,::]
b

array([[10, 10, 10]])

In [10]:
b[0,2] = 0
b

array([[10, 10,  0]])

In [11]:
print(a) # the element of a changed as well!! --> basic indexing as we did for b only returns a view!

[[10 10  0]
 [10 10 10]]


The following types of indexing are **basic**:

**Slicing:**


The basic slice syntax is `i:j:k` where i is the starting index, j is the stopping index, and k is the step.

In [12]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
a[0:8:2]

array([0, 2, 4, 6])

If you do not indicate any starting or stopping index, this means "take all the elements along this axis"!

In [14]:
a[::2]

array([0, 2, 4, 6, 8])

A negative step means start from the end of the array. A step of`-1` starts to select the entries of the array from the very end and takes each element (step = -1). So if you take all elements of one axis (`::`) and a step of `-1`, you will have your array flipped!

In [15]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [16]:
a[::-4]

array([9, 5, 1])

**Indexing with an Integer:**

In [17]:
x = np.array([[10, 20, 30],
              [40, 50, 60]])
y = x[:,2]
print(y)

[30 60]


In [18]:
y[1] = 3
x

array([[10, 20, 30],
       [40, 50,  3]])

### 9.2.2 Advanced indexing

If you select a part of your array by advanced indexing, this will create an actual **copy** of the original array! That means there is an extra memory slot used for your new array. You can now change your new array without changing the old one too. Advanced indexing is triggered when the selection occurs over an ndarray. 

    There are two ways of advaned indexing:

**Integer Indexing**: Means indexing the elements of an arrays by their coordinates inside the array. 

In [19]:
x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]]) # Lets get the corner elements of this 4x3 array:

x_coords = [0, 0, 2, 2]
y_coords = [0,3, 0, 3]

# Read the location of each element we want to select: [0,0] [0,3] [2,0] [2,3]!

y = x[y_coords, x_coords] # first the column-coords and second the row-coords!
print(y)


[ 0  9  2 11]


**Boolean Indexing**: Means indexing based on a conditions. Instead of the coordinate array, we use a boolean array!

In [20]:
a = np.array([1,2,3,4])
b = [True, True, False, True]

a[b] # only selects the elements of a, where b is true!


array([1, 2, 4])

In [21]:
a[a<3] # This internally creates a boolean array like the b array above!

array([1, 2])